### ISSUE TITLE
Error on the path using Zeit V2

### ISSUE THREAD

**Issue by Gmulti** [googleapis/nodejs-vision#383]
#### Environment details

  - OS: on zeit deployment
  - Node.js version: latest
  - npm version: latest
  - `@google-cloud/vision` version: 1.0.0

#### Steps to reproduce

You can view source online here : https://zeit.co/deployments/testvision-80c8uqjob.now.sh/source

The bug exists only on the deployment with zeit on their new version (2).
Just trying to require the library generates the error.
You can see the logs here:  https://zeit.co/gmulti/testvision/80c8uqjob/logs
And, online URL : https://testvision-80c8uqjob.now.sh

I also proposed a post on spectrum to tell them about it: 
https://spectrum.chat/zeit/serve/google-vision-1-0-0-not-work~966bc190-10ca-43a5-82c9-4d31f3c739e0

**Comment by Gmulti** [comment]
This has just been reported here : https://github.com/zeit/ncc/issues/398

**Comment by ecjs** [comment]
Same issue with `@google-cloud/datastore`

**Comment by bcoe** [comment]
@Gmulti @ecjs my guess is that this bug will crop up on all of our libraries which depend on `grpc-js`; `ncc` is not an environment we test in unfortunately.

We'll make an effort to dig into this as soon as possible, and if anything is figured out on the `ncc` side of things, we'll happily try to land a patch.

**Comment by agrohs** [comment]
Having same issue

**Comment by bcoe** [comment]
looping in @alexander-fenster, who's team works more closely with `grpc-js`.

**Comment by alexander-fenster** [comment]
As of today, most `@google-cloud/*` libraries use `@grpc/grpc-js`, `protobufjs`, and `google-auth-library`, which are the three major dependencies. @Gmulti If you could try compiling the similar single-line `require` file using these two libraries it might help to pinpoint the error to one of these dependencies.

The linked issue also says that `googleapis` also has an issue, which is weird, since `googleapis` is a very straightforward HTTP/1 client library, very different from `@google-cloud` onces (but again, it uses the auth library). So trying to pinpoint which dependency breaks everything will help solving the problem for you all.

Thanks!

**Comment by czahedi** [comment]
Hey Alex, how's this going?

**Comment by alexander-fenster** [comment]
Since the time this issue was opened, we implemented gRPC fallback support which made it possible to use the library without gRPC. I don't really know if it helps `ncc` to work. For example, it made it possible to use it with `webpack`. To make it work, pass `fallback: true` to the client constructor, and make sure that `@grpc/grpc-js` is not included into the process in any way. 

@Gmulti are you still interested in trying some tricks to solve it?

**Comment by nnegrey** [comment]
Going to close this out, if folks are still interested in trying the above, please feel free to comment again and re-open.
