### ISSUE TITLE
ImageAnnotatorClient does not work inside Electron.js

### ISSUE THREAD

**Issue by phdggg** [googleapis/nodejs-vision#573]
Hi, I am able to use ImageAnnotatorClient to call google vision API for no problem.
But when I tried to run the same code inside Electron.js. 

  const client = new vision.ImageAnnotatorClient({
    keyFilename: "key.json"
  });

The following error occurs:

Uncaught (in promise) TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object
    at validateString (internal/validators.js:112)
    at Object.basename (path.js:1157)
    at GrpcClient.loadProto (grpc.ts:166)
    at new ImageAnnotatorClient (image_annotator_client.ts:144)
    at myfunction (/Users/XXX/Demo/mycode.js:40)
    at FSReqCallback.oncomplete (fs.js:146)

It seems that the error occurred in the following code snippet inside image_annotator_client.ts

    const nodejsProtoPath = path.join(
      __dirname,
      '..',
      '..',
      'protos',
      'protos.json'
    );
    this._protos = this._gaxGrpc.loadProto(
      opts.fallback
        ? // eslint-disable-next-line @typescript-eslint/no-var-requires
          require('../../protos/protos.json')
        : nodejsProtoPath
    );

**Comment by phdggg** [comment]
I can fix this by changing this line in image_annotator_client.ts:

from
`const isBrowser = typeof window !== 'undefined';`
to
`const isBrowser = false`

I hope there is a good way to handle this, especially in the situation when people use Electron.js (having both browser and node.js)

**Comment by vishald123** [comment]
Hey @phdggg, Could you please specify more details. Nodejs version, electron version and also if you could provide your complete code. Thanks.

**Comment by alexander-fenster** [comment]
This should be working without any special changes to the client; just make sure you update your dependencies (`npm ls google-gax` should be >= 2.3.0).  In a real browser, it will just work. In Electron, since it does not follow `"browser"` field in `package.json`, please pass `{fallback: true}` to the `ImageAnnotatorClient` constructor. 

Alternatively, as discussed in https://github.com/googleapis/nodejs-speech/issues/547, just use the bundler (`webpack` and `browserify`) before using the code in Electron.

You will need to authenticate as described [here](https://github.com/googleapis/google-cloud-node/issues/2933#issuecomment-547657659) (with OAuth2) or possibly with an API key, as shown in the aforementioned nodejs-speech issue.

**Comment by tofutim** [comment]
@alexander-fenster I also have this issue. Can you give more details on using the bundler? how do we do that?

**Comment by tofutim** [comment]
seems this is fixed in the latest code:

![image](https://user-images.githubusercontent.com/157766/83099794-21f2fb00-a063-11ea-9df0-881bbbf12ae7.png)

**Comment by Pizzacus** [comment]
Here's an awful workaround:

```js
const client = new vision.ImageAnnotatorClient({
	get fallback() {
		return false
	},
	set fallback(_) {}
});
```

This forcefully prevents the fallback property from being changed.
Whenever `opts.fallback = true;` happens, nothing is done, and it remains false (whereas making it unwritable with .defineProperty() would cause a crash).
